### PR TITLE
[Strawman] Use react-dom's test suite

### PR DESCRIPTION
**Pull request by prometheansacrifice**
WIP. I'm looking for feedback, overall viability and other concerns. Basic idea: Map react-dom to react-dom-lite using jest's module mapper. Running `yarn test-rdl` inside react would run only react-dom tests, with react-dom resolving to react-dom-lite.

### CODE REVIEW

**Comment by jquense** [comment]
nice! I don't have much familiarity with git submodules, except that folks say they are hard to work with and should be avoided (no idea if that's relevant here). 

My other thought for doing this was to maybe manually pull the repo and copy the test files into a react-tests folder periodically. Might be easy than worrying about submodules (especially for others contributing), WDYT?

**Comment by prometheansacrifice** [comment]
> pull the repo and copy the test files into a react-tests folder periodically. Might be easy than worrying about submodules

Completely agreed. Just that I'm exploring ways to do it with a tool. Hate the fact that it has to be git submodules

> especially for others contributing

Ideally they must not be touched by anyone else.  I'm hoping react's tests would serve like es6's test262

**Comment by prometheansacrifice** [comment]
> I was thinking build a script that git clones react into a tmp folder, cp react-dom//tests into vendor-tests or something

Seems like a good idea. But I dont understand what you mean by

> yeah, tho if we use submodules that won't be the case, you need to somewhat aware of them to even properly clone the repo yeah?

**Comment by prometheansacrifice** [comment]
Closing this. Superseded by PR #18

**Pull request closed without merging**
