### PR TITLE
update dependencies

### LINKED ISSUE #24: Update to the latest reconciler
Would be nice to get context API support :-)

If you have any questions hit me up!

### PR DESCRIPTION
**Pull request by jquense**
closes #24

### CODE REVIEW

**Comment by prometheansacrifice** [comment]
Please hold this until [SSR](https://github.com/jquense/react-dom-lite/pull/21) lands. My concern is that we had incorrectly (minor) typed react-reconciler earlier.

**Comment by prometheansacrifice** [comment]
@jquense Can we please do this incrementally? There are a couple of places react-reconciler has changed since 0.7 (Eg: async). I'll raise a separate PR just bumping reconciler and making the respective changes.

**Comment by prometheansacrifice** [comment]
@jquense 

I finished work on the upgrading `react-reconciler` to  0.10.0. Tested it on the test-ssr-rdl repo. Please have a look.

Cleaning up dependencies
- [ ] Do we need react-dom dep?
- [ ] Invariant in two places. I'll remove the one in devDeps
- [ ] Both babel-core and @babel/core are present. Get rid of `babel-core`?
- [ ] eslint-config-jason@4.0.0" has incorrect peer dependency "eslint@^3.3.1". PR raised [here](https://github.com/jquense/eslint-config-jason/pull/2). Once merged we need to update our dep.

**Comment by prometheansacrifice** [comment]
@jquense Would you like to upgrade the rest of the dev dependencies?

**Comment by jquense** [comment]
sure 👍

**Pull request closed without merging**
